### ISSUE TITLE
SMBC broken

### ISSUE THREAD

**Issue by AlbericC** [AlbericC/comics-downloader#1]
SMBC remastered their webpage, and currently the script fails because of this. regex can't match.

**Comment by AlbericC** [comment]
```
$ ./getcomics.py
Traceback (most recent call last):
File "./getcomics.py", line 79, in <module>
only: 'what comics to grab, separated with commas'=AVAIL_COLLECTIONS):
File "/home/atrament/.virtualenvs/getsinfest/lib/python3.5/site-packages/begin/main.py", line 115, in _start
prog.start()
File "/home/atrament/.virtualenvs/getsinfest/lib/python3.5/site-packages/begin/main.py", line 54, in start
collector=self._collector)
File "/home/atrament/.virtualenvs/getsinfest/lib/python3.5/site-packages/begin/cmdline.py", line 253, in apply_options
return_value = call_function(func, signature(ext), opts)
File "/home/atrament/.virtualenvs/getsinfest/lib/python3.5/site-packages/begin/cmdline.py", line 236, in call_function
return func(*pargs, **kwargs)
File "/home/atrament/.virtualenvs/getsinfest/lib/python3.5/site-packages/begin/convert.py", line 92, in wrapper
return func(*args, **kwargs)
File "./getcomics.py", line 102, in main
comics_to_check += class_.all()
File "/home/atrament/Documents/code/git/getsinfest/comics/smbc.py", line 64, in all
return [cls(num) for num in range(cls.first_id(), cls.latest_id() + 1)]
File "/home/atrament/Documents/code/git/getsinfest/comics/smbc.py", line 51, in latest_id
matching = re.search(latest_regex, firstpage.text).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

regex can't match to first page.
